# This version spins up the production version of the reporting service with a corresponding DB
# This is useful for circle ci testing, or for testing in conjuction with the other protocol services
#
version: '3.5'

networks:
  agency-network:
    name: agency-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

services:
  protocol-reporting:
    build:
      context: ./
      dockerfile: Dockerfile.production
    image: protocol-reporting
    container_name: protocol-reporting
    working_dir: /www
    ports:
      - "3022:3022"
    expose:
      - "3022"
    networks:
      - agency-network
    tty: true
    depends_on:
      - reporting-db
    env_file:
      - ./.env

  reporting-db:
    image: postgres:11
    container_name: reporting-db
    command: postgres
    networks:
      - agency-network
    tty: true
    env_file:
      - ./.env
