version: 2.1

jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '14.15.1'
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run test

  prod-test:
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Prepare Environment
          command: |
            cp dummy.env .env
      - run:
          name: Start docker compose and ensure all services start
          command: |
            docker network prune -f
            docker-compose build --no-cache
            docker-compose up --force-recreate --abort-on-container-exit

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters: # run for all branches AND tags
            tags:
              only: /.*/
      - prod-test:
          filters: # run for all branches AND tags
            tags:
              only: /.*/
      - docker/publish:
          requires:
            - build-and-test
            - prod-test
          filters: # only run for semver tagged versions
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
            branches:
              ignore: /.*/
          update-description: true
          dockerfile: Dockerfile.production
          image: kivaprotocol/protocol-reporting
          tag: << pipeline.git.tag >>,latest

orbs:
  node: circleci/node@4.1.0
  docker: circleci/docker@1.3.0
  kube-orb: circleci/kubernetes@0.11.1
  aws-eks: circleci/aws-eks@1.0.1
  helm: circleci/helm@1.2.0
